import {
  User,
  Organization,
  Product,
  Order,
  QualityInspection,
  Rider,
  Delivery,
  Alert,
  CustomerFeedback,
  SystemSettings,
  AuditLog,
} from '@/lib/types';

export const INITIAL_SETTINGS: SystemSettings = {
  approvalScoreMin: 85,
  reviewScoreMin: 70,
  tempWarningC: 14.0,
  tempCriticalC: 22.0,
  vibrationWarningG: 0.85,
  vibrationCriticalG: 1.4,
  geminiApiKeyConfigured: false,
  supabaseConfigured: false,
  simulationIntervalMs: 3000,
};

export const INITIAL_ORGANIZATION: Organization = {
  id: 'org-freshguard-01',
  name: 'FreshGuard Express Logistics',
  slug: 'freshguard-express',
  domain: 'freshguard.ai',
  settings: INITIAL_SETTINGS,
  createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
};

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-admin-01',
    email: 'admin@freshguard.ai',
    name: 'Sarah Chen (Admin)',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    organizationId: INITIAL_ORGANIZATION.id,
    department: 'Global Operations',
    createdAt: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'usr-inspector-01',
    email: 'inspector@freshguard.ai',
    name: 'Marcus Rivera',
    role: 'QUALITY_INSPECTOR',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    organizationId: INITIAL_ORGANIZATION.id,
    department: 'Produce Intake & Grading',
    createdAt: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'usr-packer-01',
    email: 'packing@freshguard.ai',
    name: 'Elena Rostova',
    role: 'PACKING_OPERATOR',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
    organizationId: INITIAL_ORGANIZATION.id,
    department: 'Cold Hub Packing Station 4',
    createdAt: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'usr-delivery-01',
    email: 'delivery@freshguard.ai',
    name: 'David Kim',
    role: 'DELIVERY_MANAGER',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80',
    organizationId: INITIAL_ORGANIZATION.id,
    department: 'Last-Mile Fleet Control',
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'Honeycrisp Apples (Select Batch)',
    sku: 'FRU-APP-001',
    category: 'FRUITS',
    batchNumber: 'BATCH-APP-942',
    stock: 840,
    unit: 'kg',
    optimalTempMin: 1.0,
    optimalTempMax: 4.5,
    maxVibrationG: 0.7,
    fragilityScore: 4,
    freshnessIndex: 94.5,
    avgQualityScore: 92.4,
    defectRate: 1.8,
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-002',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'Organic Hass Avocados',
    sku: 'FRU-AVO-002',
    category: 'FRUITS',
    batchNumber: 'BATCH-AVO-184',
    stock: 450,
    unit: 'units',
    optimalTempMin: 5.0,
    optimalTempMax: 10.0,
    maxVibrationG: 0.45,
    fragilityScore: 8,
    freshnessIndex: 91.2,
    avgQualityScore: 88.7,
    defectRate: 3.2,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-003',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'San Marzano Vine Tomatoes',
    sku: 'VEG-TOM-003',
    category: 'VEGETABLES',
    batchNumber: 'BATCH-TOM-512',
    stock: 620,
    unit: 'kg',
    optimalTempMin: 10.0,
    optimalTempMax: 14.0,
    maxVibrationG: 0.4,
    fragilityScore: 9,
    freshnessIndex: 88.0,
    avgQualityScore: 86.1,
    defectRate: 4.5,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-004',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'Baby Spinach (Hydroponic Clamshell)',
    sku: 'VEG-SPN-004',
    category: 'LEAFY_GREENS',
    batchNumber: 'BATCH-SPN-831',
    stock: 310,
    unit: 'punnets',
    optimalTempMin: 1.0,
    optimalTempMax: 4.0,
    maxVibrationG: 0.5,
    fragilityScore: 7,
    freshnessIndex: 96.4,
    avgQualityScore: 95.2,
    defectRate: 1.1,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-005',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'California Sweet Strawberries',
    sku: 'FRU-STR-005',
    category: 'FRUITS',
    batchNumber: 'BATCH-STR-309',
    stock: 280,
    unit: 'boxes',
    optimalTempMin: 0.5,
    optimalTempMax: 3.5,
    maxVibrationG: 0.3,
    fragilityScore: 10,
    freshnessIndex: 93.1,
    avgQualityScore: 91.0,
    defectRate: 2.8,
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'prod-006',
    organizationId: INITIAL_ORGANIZATION.id,
    name: 'Artisan Rustic Sourdough',
    sku: 'BAK-SOU-006',
    category: 'BAKERY',
    batchNumber: 'BATCH-BAK-112',
    stock: 120,
    unit: 'loaves',
    optimalTempMin: 18.0,
    optimalTempMax: 22.0,
    maxVibrationG: 0.8,
    fragilityScore: 5,
    freshnessIndex: 98.0,
    avgQualityScore: 97.4,
    defectRate: 0.5,
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=600&q=80',
    createdAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_RIDERS: Rider[] = [
  {
    id: 'rider-01',
    name: 'Alex Vance',
    phone: '+1 (555) 234-5678',
    vehicleType: 'E_BIKE',
    vehiclePlate: 'EB-902',
    status: 'ON_DELIVERY',
    activeDeliveriesCount: 1,
    totalDeliveries: 412,
    successfulDeliveries: 408,
    handlingScore: 98.4,
    damageIncidents: 1,
    avgDeliveryTimeMinutes: 16.2,
    reliabilityScore: 99.1,
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    zone: 'Downtown Core Zone A',
  },
  {
    id: 'rider-02',
    name: 'Samir Patel',
    phone: '+1 (555) 345-6789',
    vehicleType: 'MOTORBIKE',
    vehiclePlate: 'MB-441',
    status: 'AVAILABLE',
    activeDeliveriesCount: 0,
    totalDeliveries: 320,
    successfulDeliveries: 312,
    handlingScore: 94.2,
    damageIncidents: 2,
    avgDeliveryTimeMinutes: 18.5,
    reliabilityScore: 97.5,
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    zone: 'Westside Residential',
  },
  {
    id: 'rider-03',
    name: 'Chloe Martin',
    phone: '+1 (555) 456-7890',
    vehicleType: 'VAN',
    vehiclePlate: 'VN-108',
    status: 'AVAILABLE',
    activeDeliveriesCount: 0,
    totalDeliveries: 580,
    successfulDeliveries: 574,
    handlingScore: 97.9,
    damageIncidents: 1,
    avgDeliveryTimeMinutes: 21.0,
    reliabilityScore: 98.9,
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
    zone: 'Harbor Commercial District',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-881',
    orderNumber: 'FG-2026-881',
    organizationId: INITIAL_ORGANIZATION.id,
    customerName: 'Claire Beauchamp',
    customerAddress: '452 Pinecrest Ave, Apt 4B, Metro Heights',
    customerPhone: '+1 (555) 912-3344',
    items: [
      {
        id: 'item-881-1',
        orderId: 'ord-881',
        productId: 'prod-005',
        productName: 'California Sweet Strawberries',
        sku: 'FRU-STR-005',
        category: 'FRUITS',
        quantity: 2,
        unitPrice: 5.99,
        unit: 'boxes',
        qualityScore: 94,
        inspected: true,
      },
      {
        id: 'item-881-2',
        orderId: 'ord-881',
        productId: 'prod-004',
        productName: 'Baby Spinach (Hydroponic Clamshell)',
        sku: 'VEG-SPN-004',
        category: 'LEAFY_GREENS',
        quantity: 1,
        unitPrice: 4.49,
        unit: 'punnets',
        qualityScore: 96,
        inspected: true,
      },
    ],
    totalAmount: 16.47,
    status: 'OUT_FOR_DELIVERY',
    qualityStatus: 'APPROVED',
    packingStatus: 'PACKED',
    deliveryStatus: 'IN_TRANSIT',
    riderId: 'rider-01',
    riderName: 'Alex Vance',
    handlingRisk: 'LOW',
    deliveryEta: new Date(Date.now() + 12 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 24 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ord-882',
    orderNumber: 'FG-2026-882',
    organizationId: INITIAL_ORGANIZATION.id,
    customerName: 'Marcus Sterling',
    customerAddress: '120 Ocean View Blvd, Suite 12, West Bay',
    customerPhone: '+1 (555) 887-2211',
    items: [
      {
        id: 'item-882-1',
        orderId: 'ord-882',
        productId: 'prod-003',
        productName: 'San Marzano Vine Tomatoes',
        sku: 'VEG-TOM-003',
        category: 'VEGETABLES',
        quantity: 3,
        unitPrice: 3.89,
        unit: 'kg',
        qualityScore: 89,
        inspected: true,
      },
      {
        id: 'item-882-2',
        orderId: 'ord-882',
        productId: 'prod-002',
        productName: 'Organic Hass Avocados',
        sku: 'FRU-AVO-002',
        category: 'FRUITS',
        quantity: 4,
        unitPrice: 2.25,
        unit: 'units',
        qualityScore: 88,
        inspected: true,
      },
    ],
    totalAmount: 20.67,
    status: 'PACKING',
    qualityStatus: 'APPROVED',
    packingStatus: 'IN_PROGRESS',
    deliveryStatus: 'ASSIGNED',
    riderId: 'rider-02',
    riderName: 'Samir Patel',
    handlingRisk: 'LOW',
    deliveryEta: new Date(Date.now() + 35 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ord-883',
    orderNumber: 'FG-2026-883',
    organizationId: INITIAL_ORGANIZATION.id,
    customerName: 'Evelyn Reed',
    customerAddress: '78 Elmwood Terrace, East District',
    customerPhone: '+1 (555) 441-9988',
    items: [
      {
        id: 'item-883-1',
        orderId: 'ord-883',
        productId: 'prod-001',
        productName: 'Honeycrisp Apples (Select Batch)',
        sku: 'FRU-APP-001',
        category: 'FRUITS',
        quantity: 2.5,
        unitPrice: 4.2,
        unit: 'kg',
        inspected: false,
      },
    ],
    totalAmount: 10.5,
    status: 'INSPECTION',
    qualityStatus: 'PENDING',
    packingStatus: 'PENDING',
    deliveryStatus: 'UNASSIGNED',
    handlingRisk: 'LOW',
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ord-884',
    orderNumber: 'FG-2026-884',
    organizationId: INITIAL_ORGANIZATION.id,
    customerName: 'Jonathan Hayes',
    customerAddress: '314 Market Square, Floor 2, Central Plaza',
    customerPhone: '+1 (555) 332-1100',
    items: [
      {
        id: 'item-884-1',
        orderId: 'ord-884',
        productId: 'prod-006',
        productName: 'Artisan Rustic Sourdough',
        sku: 'BAK-SOU-006',
        category: 'BAKERY',
        quantity: 2,
        unitPrice: 6.5,
        unit: 'loaves',
        qualityScore: 98,
        inspected: true,
      },
    ],
    totalAmount: 13.0,
    status: 'DELIVERED',
    qualityStatus: 'APPROVED',
    packingStatus: 'PACKED',
    deliveryStatus: 'DELIVERED',
    riderId: 'rider-03',
    riderName: 'Chloe Martin',
    handlingRisk: 'LOW',
    completedAt: new Date(Date.now() - 120 * 60000).toISOString(),
    createdAt: new Date(Date.now() - 180 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_INSPECTIONS: QualityInspection[] = [
  {
    id: 'insp-001',
    orderId: 'ord-881',
    productId: 'prod-005',
    productName: 'California Sweet Strawberries',
    batchNumber: 'BATCH-STR-309',
    inspectorId: 'usr-inspector-01',
    inspectorName: 'Marcus Rivera',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80',
    overallScore: 94,
    freshnessScore: 96,
    appearanceScore: 95,
    ripenessScore: 92,
    riskLevel: 'LOW',
    decision: 'APPROVED',
    defects: [],
    aiExplanation:
      'Uniform ruby-red pigmentation, firm calyx integrity with vivid green sepals. Zero fungal mycelium or micro-bruising detected across surface contours.',
    recommendation: 'Exceptional export-grade batch. Approved for expedited smart packing with ventilated eco-tray.',
    shelfLifeEstimateDays: 5,
    packagingAdvice: 'Ventilated rigid clamshell with cellulose moisture-absorption pad.',
    inspectedAt: new Date(Date.now() - 40 * 60000).toISOString(),
    isAiGenerated: true,
  },
  {
    id: 'insp-002',
    orderId: 'ord-882',
    productId: 'prod-003',
    productName: 'San Marzano Vine Tomatoes',
    batchNumber: 'BATCH-TOM-512',
    inspectorId: 'usr-inspector-01',
    inspectorName: 'Marcus Rivera',
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    overallScore: 89,
    freshnessScore: 90,
    appearanceScore: 88,
    ripenessScore: 89,
    riskLevel: 'LOW',
    decision: 'APPROVED',
    defects: [
      {
        id: 'def-01',
        type: 'BRUISE',
        severity: 'MINOR',
        locationDescription: 'Micro-compression on lateral shoulder (<3mm), cuticle intact.',
        confidence: 0.92,
      },
    ],
    aiExplanation:
      'High turgidity, deep carotene hue. Minor mechanical pressure indentation noted on one fruit, skin barrier remains uncompromised.',
    recommendation: 'Approved for standard delivery. Apply cushioned air-cell dividers during packing to prevent transit pressure.',
    shelfLifeEstimateDays: 6,
    packagingAdvice: 'Cushioned air-cell tray to prevent contact bruising.',
    inspectedAt: new Date(Date.now() - 50 * 60000).toISOString(),
    isAiGenerated: true,
  },
];

export const INITIAL_DELIVERIES: Delivery[] = [
  {
    id: 'del-001',
    orderId: 'ord-881',
    orderNumber: 'FG-2026-881',
    riderId: 'rider-01',
    riderName: 'Alex Vance',
    customerName: 'Claire Beauchamp',
    destinationAddress: '452 Pinecrest Ave, Apt 4B, Metro Heights',
    destinationArea: 'Metro Heights',
    distanceKm: 3.8,
    status: 'IN_TRANSIT',
    riskLevel: 'LOW',
    dispatchedAt: new Date(Date.now() - 14 * 60000).toISOString(),
    estimatedDeliveryTime: new Date(Date.now() + 10 * 60000).toISOString(),
    currentTelemetry: {
      id: 'tel-001',
      deliveryId: 'del-001',
      orderId: 'ord-881',
      timestamp: new Date().toISOString(),
      temperatureC: 3.4,
      humidityPercent: 88.5,
      vibrationG: 0.28,
      accelerationG: 0.12,
      speedKmh: 19.4,
      latitude: 37.7749,
      longitude: -122.4194,
      handlingRisk: 'LOW',
    },
    recentEvents: [],
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alt-001',
    organizationId: INITIAL_ORGANIZATION.id,
    type: 'TEMPERATURE',
    severity: 'WARNING',
    title: 'Cold-Chain Fluctuation Warning',
    message: 'Hub 2 Chilled Produce Cellar recorded 7.2°C (Optimal max: 4.5°C) for 14 minutes.',
    entityType: 'SYSTEM',
    isRead: false,
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'alt-002',
    organizationId: INITIAL_ORGANIZATION.id,
    type: 'QUALITY',
    severity: 'INFO',
    title: 'Batch BATCH-STR-309 Grade A Cleared',
    message: 'AI Quality Inspector cleared California Sweet Strawberries at 94% quality score.',
    entityType: 'INSPECTION',
    entityId: 'insp-001',
    isRead: false,
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'alt-003',
    organizationId: INITIAL_ORGANIZATION.id,
    type: 'DELIVERY',
    severity: 'INFO',
    title: 'Dispatch Initiated: Order FG-2026-881',
    message: 'Rider Alex Vance has picked up delivery for Claire Beauchamp.',
    entityType: 'DELIVERY',
    entityId: 'del-001',
    isRead: true,
    createdAt: new Date(Date.now() - 14 * 60000).toISOString(),
  },
];

export const INITIAL_FEEDBACK: CustomerFeedback[] = [
  {
    id: 'fb-001',
    orderId: 'ord-884',
    orderNumber: 'FG-2026-884',
    customerName: 'Jonathan Hayes',
    rating: 5,
    freshnessRating: 5,
    packagingRating: 5,
    deliverySpeedRating: 5,
    comment: 'The artisanal sourdough arrived still warm with a crisp crust! Incredible packaging and very polite courier.',
    isDamageReported: false,
    createdAt: new Date(Date.now() - 100 * 60000).toISOString(),
  },
  {
    id: 'fb-002',
    orderId: 'ord-879',
    orderNumber: 'FG-2026-879',
    customerName: 'Samantha Wu',
    rating: 4,
    freshnessRating: 5,
    packagingRating: 4,
    deliverySpeedRating: 4,
    comment: 'Apples were remarkably crisp and sweet. No bruises at all. Delivery took 3 minutes longer than expected due to rain.',
    isDamageReported: false,
    createdAt: new Date(Date.now() - 240 * 60000).toISOString(),
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'log-01',
    userId: 'usr-admin-01',
    userName: 'Sarah Chen',
    action: 'SYSTEM_BOOT',
    entity: 'SYSTEM',
    entityId: 'sys-01',
    metadata: { version: 'FreshGuard AI v2.4.0', environment: 'production-ready' },
    timestamp: new Date(Date.now() - 360 * 60000).toISOString(),
  },
  {
    id: 'log-02',
    userId: 'usr-inspector-01',
    userName: 'Marcus Rivera',
    action: 'INSPECTION_COMPLETED',
    entity: 'QUALITY_INSPECTION',
    entityId: 'insp-001',
    metadata: { product: 'California Sweet Strawberries', score: 94, decision: 'APPROVED' },
    timestamp: new Date(Date.now() - 40 * 60000).toISOString(),
  },
];
